name: Release update

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: Artifact name
        type: string
        required: true
      tagName:
        description: Tag name
        type: string
        required: true
      prerelease:
        description: Prerelease
        type: boolean
        required: true
      releaseName:
        description: Release name
        type: string
        required: true

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepMarketRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: ${{ github.event.inputs.artifactName }}
